// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    LayoutAside: typeof import('./components/LayoutAside.vue')['default']
    LayoutAsideMenu: typeof import('./components/LayoutAsideMenu.vue')['default']
    LayoutBreadcrumb: typeof import('./components/LayoutBreadcrumb.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutPageHeader: typeof import('./components/LayoutPageHeader.vue')['default']
    LayoutTabs: typeof import('./components/LayoutTabs.vue')['default']
    MultiWindowKeepAlive: typeof import('./components/multi-window/components/MultiWindowKeepAlive.vue')['default']
    MultiWindowRouter: typeof import('./components/multi-window/components/MultiWindowRouter.vue')['default']
    MultiWindowRouterTransition: typeof import('./components/multi-window/components/MultiWindowRouterTransition.vue')['default']
  }
}

export { }
